### ISSUE TITLE
About Page Link Issue

### ISSUE THREAD

**Issue by jamesjpk123** [marblelympics/marblelympics.github.io#1]
On the about page, (https://marblelympics.github.io/about/) there is text that says this at the bottom: "This website was created for fun and the author does not claim any right to the data or videos presented here." The problem is, is that there is no link when it says "here".

**Comment by rrraptor** [comment]
I expected here to mean, on this website. I guess I could be more explicit if it's confusing.

**Comment by jamesjpk123** [comment]
Ohhhhh. With all the here before it ("Issues can be reported here."), I assumed there was a missing link.
