### ISSUE TITLE
Make tab picture look nicer

### ISSUE THREAD

**Issue by jamesjpk123** [marblelympics/marblelympics.github.io#15]
In the tab picture:
![capture](https://user-images.githubusercontent.com/18013689/28741636-eeb8e962-73d7-11e7-9de6-c0e2ba88d17e.PNG)
It looks like the image on the left is squashed like the dimensions don't match. Also, it has an unsightly white background. We should get a logo that has a transparent background and correct dimensions.

**Comment by rrraptor** [comment]
done
