### ISSUE TITLE
Specify Image Dimensions

### ISSUE THREAD

**Issue by jamesjpk123** [marblelympics/marblelympics.github.io#16]
When running a chrome dev tools audit, I found this issue:
![capture](https://user-images.githubusercontent.com/18013689/28741658-77073dbe-73d8-11e7-84d5-20f36c50047e.PNG)
It is saying to specify the image dimensions in the code of this image:
![capture](https://user-images.githubusercontent.com/18013689/28741662-9c3962ec-73d8-11e7-9976-9fc7598477b5.PNG)
Since I can't pinpoint any HTML in this project, this is out of my league. Can anyone help see why this image isn't specified with a height and width? (This would help the page load faster in the long run)

**Comment by rrraptor** [comment]
done
