### ISSUE TITLE
Purple Stars link pull issue

### ISSUE THREAD

**Issue by jamesjpk123** [marblelympics/marblelympics.github.io#2]
On the purple stars page (https://marblelympics.github.io/teams/purple-stars/), it has an error trying to pull "Purple stars banner image". Here is a photo:
![capture](https://user-images.githubusercontent.com/18013689/28697342-578c3128-72f8-11e7-936a-584ca15dbb4d.PNG)

**Comment by rrraptor** [comment]
Jelle hasn't made a banner for either of these teams yet.

**Comment by jamesjpk123** [comment]
Like I said on issue #4, do you think we could get a sample image (full comment there)?

**Comment by rrraptor** [comment]
hid with css
