### ISSUE TITLE
Discord

### ISSUE THREAD

**Issue by TheMinecraftBrick** [marblelympics/marblelympics.github.io#20]
As another way for die hard fans to communicate, we've created a discord. The more People we can get on there, the better. As discord is much faster means of communication for huge groups like us, vs things like reddit and a wiki. Perhaps if there was a way to integrate the discord into the site so people can join it, that'd be cool. Thanks!
Discord:
[https://discord.gg/kTT2TZ](url)

**Comment by jamesjpk123** [comment]
I could add that.

**Comment by jamesjpk123** [comment]
Looks like the invite is expired @TheMinecraftBrick, can you produce a permanent invite with discord? One that won't expire after some time or clicks?

**Comment by TheMinecraftBrick** [comment]
@jamesjpk123 Oh im so sorry, one moment, theres the new one:
https://discord.gg/6brFYYU

**Comment by rrraptor** [comment]
This would probbly be the cleanest solution: https://blog.discordapp.com/add-the-discord-widget-to-your-site-d45ffcd718c6

**Comment by rrraptor** [comment]
There are 2 semi-official (?) discords now, not really willing to wade into this one.
