### ISSUE TITLE
Would you be willing to help us?

### ISSUE THREAD

**Issue by CissyRene** [marblelympics/marblelympics.github.io#23]
Hey, so my name is Cissy. I just found your ML fan site and it is amazing. The Inside the ML team (IMC) is trying to update the wiki to get each teams page looking the same. We were wondering if you or you all would be willing to help? 

Contact me for more info!

Thank you, 
Cissy
IMC

**Comment by rrraptor** [comment]
Thanks! This site generates all pages from one source of data. Wikis, on the other hand, have data everywhere that's all mutable and not related. Wikis work great for prose, but are terrible for data, in my experience. I don't like the idea of updating 28 team pages, a season page, an event page, and all the secondary analysis pages every time an event happens or needs to be tweaked so I probably won't be any help. Though, it seems like there are quite a few people that don't see this as a hurdle.

Also the Wikia platform itself throws ads on everything and randomly Luke Skywalker or Game of Thrones in the margins for no apparent reason. It also doesn't let you have full control of the site css, layout and styling.

I mostly made this site to test out a static site generator I've been working on. I don't really have time to dedicate to updating a wiki. Good luck with everything on your end though.
