### ISSUE TITLE
Gliding Glaciers link pull issue

### ISSUE THREAD

**Issue by jamesjpk123** [marblelympics/marblelympics.github.io#3]
On the gliding glaciers page (https://marblelympics.github.io/teams/gliding-glaciers/), it has an error trying to pull "Gliding glaciers banner image". Here is a photo:
![capture](https://user-images.githubusercontent.com/18013689/28697373-a422e5a4-72f8-11e7-8f5e-6b0193ccd339.PNG)

**Comment by rrraptor** [comment]
Jelle hasn't made a banner for either of these teams yet.

**Comment by jamesjpk123** [comment]
Like I said on issue #4, do you think we could get a sample image (full comment there)?

**Comment by rrraptor** [comment]
hid with css
