### ISSUE TITLE
Quicksilvers link pull issue

### ISSUE THREAD

**Issue by jamesjpk123** [marblelympics/marblelympics.github.io#4]
On the Quicksilvers page (https://marblelympics.github.io/teams/quicksilvers/), it has an error trying to pull "Quicksilvers member image". Here is a photo:
![capture](https://user-images.githubusercontent.com/18013689/28697415-0013fe48-72f9-11e7-96dc-a84e895577ae.PNG)

**Comment by rrraptor** [comment]
The member image doesn't exist or at least I couldn't find a high resolution pic for quicksilvers like Jelle has for all the other teams.

**Comment by jamesjpk123** [comment]
Do you think we could fill it with a sample image (Like the Marblelympics logo) until we get assets?

**Comment by rrraptor** [comment]
just hid with css
