### ISSUE TITLE
Tournament 7 Data Missing

### ISSUE THREAD

**Issue by jamesjpk123** [marblelympics/marblelympics.github.io#5]
I am going to try to create a file for the data! :D

**Comment by jamesjpk123** [comment]
Ok, I finished all the data except for the final data.

**Comment by jamesjpk123** [comment]
Soon will be done

**Comment by rrraptor** [comment]
Sorry just saw this. Cool, make a PR once you're done. I can flesh out the README, didn't expect anyone to help out. I pushe some 7 stuff up before I saw this, but didn't get around to doing the heats.

**Comment by jamesjpk123** [comment]
Cool! Just wondering, what are your referring to when you've say PR?

**Comment by rrraptor** [comment]
I don't know how familiar you are with git, but a PR is a pull request. If you want, you can create a file or modify one of mine and I can pull your code into the site.

**Comment by jamesjpk123** [comment]
Ohhhh! I am familiar, but didn't know the acronym ;)

**Comment by jamesjpk123** [comment]
Ok, right [here](https://github.com/jamesjpk123/marblelympics.github.io/blob/patch-1/data/events/2017-marblelympics-tournament-7-draft.toml), I have all the data done down to the "//THIS IS WHERE I ENDED!" part of it. It is night where I live, so I will continue to work on this in the morning (about 8-12 hours from now). I expect to be done really quickly, as I am in the home stretch!

**Comment by jamesjpk123** [comment]
Ok, I created a pull request for the data! :D #6

**Comment by jamesjpk123** [comment]
#6

**Comment by jamesjpk123** [comment]
As the data has been merged, this issue is now closed! Thanks @rrraptor! :D
